layout_spectrum: 0.012306862976402044
typography_spectrum: 0.7981987339444458
color:
  brandStrength: 0.2863018966745585
  lightness: 0.1615521046333015
  saturation: 0.7315092058852315
  rhythmicContrast: 0.10388470953330398
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ca8b42c-7171-4a02-a589-2900fca045ed.png
name: The Roots Deep
navigation:
  - name: ABOUT US
    id: a2714da8-46f7-4dc2-8e15-24c882f3ab87
    type: content
  - name: SHOP
    url: 'http://therootsdeep.tictail.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ee947e7f-4e9f-468c-bda6-e90de5ec102b.jpg
title: Positive Vibes
